### ISSUE TITLE
Mapa no centra en pines en el resultado

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#1]
Mostrar 5 resultados en el mapa, centrándose en el resultado e incluyendo la ubicación del usuario

**Comment by fernandouval** [comment]
Se hizo bound para los primeros 4 establecimientos y la ubicación del usuario (si hubiera)

**Comment by fernandouval** [comment]
Se agregó resize de los mapas y se cambió ubicación en el html para que quede bien
