### ISSUE TITLE
Revisión de evaluación técnica.

### ISSUE THREAD

**Issue by Crusiris** [datauy/ElijoEstudiar#103]
Este issue forma parte de un procesos de revisión de la piloto @BID-COMUNIDADES/laboratoria-code-squads de la iniciativa Código para el desarrollo de @EL-BID.
## Issue de revisión de evaluación técnica:

Al haber contrastado la información presentadas en el repo oficial con los campos solicitados en la plantilla de [README.md](https://github.com/datauy/ElijoEstudiar/blob/master/README.md) hemos encontrado los siguiente puntos a mejorar:

- [x] Agregar el microservicio de reportes de evaluación estática de código de Sonarcloud, teniendo en cuenta que las condiciones ideales de los reportes son: 

            1 Ausencia de fallos estructurales
            2 Menos del 25% de líneas duplicadas
            3 Menos de 10 problemas críticos
            4 Más del 50% de clases, interfaces y métodos documentados
            5 Deuda técnica menor a 30 días
            6 Cobertura de test más del 25%

- [x] Agregar el badge de este servicio visible en el readme.md.
- [ ] Agregar el microservicio de integración continua de código (opcional).
- [x] Agregar el badge de este servicio visible en el readme.md (opcional).
- [x] Actualizar versión de todas las dependencias.

**Comment by knlopenknowledge** [comment]
Hola @danielcarranza nos avisan si tienen preguntas sobre el uso de sonarcloud. Es el punto obligatorio para la evaluación técnica. 
Pueden registrarse gratuitamente con su cuenta de github y vincular este repo con ese servicio y solo les tomará unos minutos para poder visibilizar el reporte del último commit. Luego de eso les pedimos que como indican las laboratorians agreguen el badge de este servicio en el readme.md. Quedamos atentos. gracias!

**Comment by knlopenknowledge** [comment]
Gracias por el aviso @danielcarranza , veo que en la linea de consulta generada respondieron con un fix:
Excluding your folder www/lib from the analysis should fix your project, you can set sonar.exclusions to www/lib/**/*, [see the documentation here.](https://sonarcloud.io/documentation/project-administration/narrowing-the-focus/)

Cuando tengan el badge favor de incluirlo en el readme.md con esto podriamos pasar a publicar la herramienta en code.iadb.org. Gracias por todo el trabajo. Un abrazo!

**Comment by danielcarranza** [comment]
@knlopenknowledge Gracias, lo habíamos visto si :)
Ahora sí quedó andando [![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=datauy_ElijoEstudiar&metric=alert_status)](https://sonarcloud.io/dashboard?id=datauy_ElijoEstudiar)
¡Ya quedó el badge en el readme!
