### ISSUE TITLE
Loading screen para evitar clicks 

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#2]

**Comment by fernandouval** [comment]
Listo, pueden quedar detalles, pero lo grueso quedó...

**Comment by danielcarranza** [comment]
Se ve el GIF al cargar y está demasiado grande.
Página 3 mobile

**Comment by despinoUY** [comment]
Le acabo de hacer un arreglo para que quedara el gif centrado y en un tamaño un poco más normal.

**Comment by fernandouval** [comment]
Se actualizó lógica para que oculte items anteriores antes de desplegar nuevos
