### ISSUE TITLE
Modificar pantalla del centro

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#24]
- [x] Turnos para el curso elegido
- [x] Listado de cursos

**Comment by fernandouval** [comment]
Faltan botones de redes del centro y botones para compartir?

**Comment by danielcarranza** [comment]
Usaría los mismos del footer (yo te4 paso un SVG de instagram al toque cuando lo encares).
Asumo que son SVG y los podés colorear del celeste del sitio. Si no yo te saco tres SVG celestes en 5 minutos.

**Comment by danielcarranza** [comment]
Quedó en Zeplin diseño: https://app.zeplin.io/project/58f7a283fff0de5abc764f53/screen/5ce7ed3f3480691e05c34bc1

**Comment by HiroAgustin** [comment]
Creé una PR ☝️

**Comment by danielcarranza** [comment]
¡Gracias Agustín!
