### ISSUE TITLE
Pedir datos que nos comentaron en taller UTU

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#34]
- [x] Planilla con sectores de estudio para cada curso
- [x] Modalidades (presencial, semipresencial, etc.) para cada curso
  - [x] En la columna "modalidad" están los convenios
- [ ] Datos de infraestructura y equipo docente hablar con estadística, gestión escolar y recursos humanos
- [ ] Ver si hay más datos de Educación Especial con Laura Grassi, referente de integración
- [ ] Horarios se pide a informática

**Comment by danielcarranza** [comment]
Correo enviado.

**Comment by fernandouval** [comment]
Se recibió planilla con los datos indicados. Se mantuvo contacto con área de educación inclusiva durante la reunión. Se pide no llamar Educación Especial sino Soporte educativo y se realizarán recomenaciones en base a lineamientos de ANEP
