### ISSUE TITLE
Ajustes en listado de cursos (+info, tags, etc.) - ¿Qué querés estudiar?

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#46]
- [x] Agregar botones "**Más información del curso**"
- [x] Arreglar cómo se muestran tags
- [x] Agregar animación al despliegue de resultados
- [x] Agrandar altura del listado de resultados

**Comment by fernandouval** [comment]
@agustinkry alguna sugerencia de efecto que podamos dar? Sobretodo pensando en la parte de los listados... si tenés algún css bajo la manga nos ayudaría bastante :)...

**Comment by fernandouval** [comment]
Hecho
