### ISSUE TITLE
Permitir cerrar (acordeón) listados por subsistema

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#47]
- [ ] En la búsqueda de cursos
- [ ] En listado completo de cursos

**Comment by danielcarranza** [comment]
Diseño en la búsqueda de cursos: https://app.zeplin.io/project/58f7a283fff0de5abc764f53/screen/5ce863c6bad4171e3bef8179

**Comment by fernandouval** [comment]
Quedó
