### ISSUE TITLE
Definir metadata para compartir por redes

### ISSUE THREAD

**Issue by fernandouval** [datauy/ElijoEstudiar#49]
En general y en particular para las páginas de resultados de búsqueda y en centros educativos.

**Comment by danielcarranza** [comment]
Ya paso texto, pero para la imagen necesitamos el logo. Agregué etiqueta "Requiere diseño" y sumé a @agustinkry a la tarea.

**Comment by danielcarranza** [comment]
> En ElijoEstudiar.uy, podés encontrar dónde seguir o volver a estudiar, con información de todas las opciones y centros de Educación Inicial, Primaria, Secundaria, UTU y Formación en Educación. ¡Usalo y compartilo!

**Comment by danielcarranza** [comment]
Compartir búsqueda
> ¡Mirá lo que encontré en #ElijoEstudiar! Vos también podés encontrar los cursos que te interesen en Educación Inicial, Primaria, Secundaria, UTU y Formación en Educación. ¡Usalo y compartilo!

**Comment by danielcarranza** [comment]
Compartir centro
> ¡Mirá lo que encontré en #ElijoEstudiar! Vos también podés encontrar el centro que te interese en Educación Inicial, Primaria, Secundaria, UTU y Formación en Educación. ¡Usalo y compartilo!

**Comment by danielcarranza** [comment]
- [ ] Agregar Instagram
- [ ] Agregar WhatsApp

**Comment by danielcarranza** [comment]
![ElijoEstudiar horizontal](https://user-images.githubusercontent.com/1755382/69345239-92056c00-0c4f-11ea-8280-35a2c74e6372.png)

**Comment by danielcarranza** [comment]
¿Cerramos¿
