### ISSUE TITLE
Mejoras recomendadas por Agustín Díaz, para las cosas hechas antes

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#50]

**Comment by Vitoartois** [comment]
https://docs.google.com/document/d/1yoIi3v_XSwqDMgUx1Tcvvv4ZZBx-1RZ_CCtprhz-I_U/edit

**Comment by danielcarranza** [comment]
https://github.com/datauy/ElijoEstudiar/pull/48

**Comment by fernandouval** [comment]
Se agrega a documentación de proceso
