### ISSUE TITLE
Descripciones de liceos

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#52]
### Listos para agregar
- [x] Webs liceos
https://drive.google.com/open?id=1ppatPtKGfarMtaGzExixeVEa06_2VxdsqZ8OlevzCyg
- [ ] Matrícula por centros (todos los subsistemas)
https://drive.google.com/open?id=0B_nO6LeGh9areVc5SWRoNFVTUjdnaERPS1Z4dU9WS0VXc3lr
- [x] Planes de secundaria
https://drive.google.com/open?id=1ImSfJ9u1KIK7B-020cfbZdqb_bYeomwW3ARUdstPGZM
- [x] Descripciones liceos
https://drive.google.com/open?id=1qXP0CNmbx9-Zd1TLaXhnFu1WbBYbi2vroOv1xZjSf7Q
- [x] Oferta 2019 CFE
https://drive.google.com/open?id=0B_nO6LeGh9arZC1fWmlOQkxoT01jTWtrZGhnYWFJYXdSbkpZ
- [x] Planes/Cursos CETP
https://docs.google.com/spreadsheets/d/1vPL6NEwf0cbB5SivkSSNg-5vrx74e8BEwN9b_7bObTU/edit#gid=250626248

**Comment by danielcarranza** [comment]
Ésta es la lista de datos que podemos meter @fernandouval. La que te comenté hoy.

**Comment by fernandouval** [comment]
@danielcarranza hay que revisar las descripciones, la de artigas tiene un salto que no sé si es que falta algo o es así. El importador está pronto y la planilla cuando se descraga tiene RULE y RUEE :sake:

**Comment by fernandouval** [comment]
Se crearon/actualizaron 273 nodos, no se procesaron 29 por no tener datos. Fallaron 23
De los 23 que fallaron por lo que estuve viendo hay recuperables, todos les falta algún dato, pero se puede sacar por acá: https://elijoestudiar-backend.development.datauy.org/establecimiento-por-rule o en prod, es una vista que permite poner filtros por ejemplo el de progreso sale sólo con el ruee: https://elijoestudiar-backend.development.datauy.org/establecimiento-por-rule?field_rule_value=&field_ruee_value=1203075

**Comment by danielcarranza** [comment]
Arreglado lo de Artigas y desoculté rule/ruee

**Comment by danielcarranza** [comment]
¿Me equivoco o este está para cerrar?
