### ISSUE TITLE
Footer por debajo de lo que se ve en pantalla

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#6]

**Comment by fernandouval** [comment]
Verificar botones en celular Página 3

**Comment by despinoUY** [comment]
Quedó arreglado en el controlador del form porque se está seteando el min-height ahí. Luego de mañana habría que eliminar eso y cambiarlo a media query y hacer un pequeño refactor al rendering de ese form.

**Comment by danielcarranza** [comment]
¿No está para cerrar ésto?

**Comment by fernandouval** [comment]
Yes, quedó con las mejoras generales de diseno del sitio
