### ISSUE TITLE
Cambiar títulos en sección “educación especial”

### ISSUE THREAD

**Issue by Vitoartois** [datauy/ElijoEstudiar#60]
Estamos a la espera a que nos confirmen la forma correcta (tal vez sea “sistema de apoyo”).

- [ ] UTU nos pasa la forma de denominación correcta

- [ ] UTU nos pasa el listado de ellos por sistema de apoyo

- [ ] Cambiarlo en la plataforma

**Comment by fernandouval** [comment]
Se hizo por recomendaciones de ANEP
