### ISSUE TITLE
corregir la url en datos UTU

### ISSUE THREAD

**Issue by Vitoartois** [datauy/ElijoEstudiar#61]
Tiene que ir a cursos.utu.edu.uy
https://docs.google.com/spreadsheets/d/1vPL6NEwf0cbB5SivkSSNg-5vrx74e8BEwN9b_7bObTU/edit#gid=250626248
Ver Datos que tenemos y hay que ver cómo agregar #52

**Comment by fernandouval** [comment]
Ya están en listado
