### ISSUE TITLE
Repaso final - Home

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#62]
![image](https://user-images.githubusercontent.com/1755382/63188755-a6c2da00-c038-11e9-809f-55342364b58d.png)

- [x] Logo
- [x] Texto introductorio
- [x] Botón "atrás" no aplica acá
- [x] Grosor incorrecto SVG del menú
- [x] ¿Botón debería decir "Dónde o qué estudiar"?

**Comment by fernandouval** [comment]
Revisar botón atrás (quedó oculto) y grosor de barras (yo veo 1 más gruesa no sé porqué :S)

**Comment by fernandouval** [comment]
Listo
