### ISSUE TITLE
Repaso final - Menú

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#63]
![image](https://user-images.githubusercontent.com/1755382/63189637-c78c2f00-c03a-11e9-8198-ed5655813a95.png)

- [x] Llegar hasta abajo
- [x] Espaciar ítems
- [x] Hacer hover/click como en diseño
- [x] Menú no cierra al hacer click
- [x] Grosor de SVG de cruz de cerrar está mal
- [x] Flecha de retorno queda por encima del menú
- [x] Botones compartir como los del home y el diseño

Ref. diseño:
![Main Menu](https://user-images.githubusercontent.com/1755382/63189677-e4286700-c03a-11e9-8bc9-251eb32c9d12.png)

**Comment by fernandouval** [comment]
Faltan un par de puntos...

**Comment by fernandouval** [comment]
Hacer hover/click como en diseño??? No me doy cuenta :( 
Lo otro es que el chiclet de menú queda bien chiquito... demasiado para mi gusto, sobretodo porque que hay que embocarle al dibujo...

**Comment by danielcarranza** [comment]
Lo hacemos en amarillo, pero sin el subrayado.

**Comment by danielcarranza** [comment]
Falta el active/secciones

**Comment by fernandouval** [comment]
Lesto
