### ISSUE TITLE
Repaso final - Formulario

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#64]
![image](https://user-images.githubusercontent.com/1755382/63378546-d4758f00-c368-11e9-8b25-9af31bfbfa8a.png)

- [x] Alineación y estilo de botones "+" y "-"
- [x] Mejorar cabezales de secciones lista que se despliega. Agrandar texto y flecha, quizás agregar hover para incentivar el click.
- [x] ¿Podemos hacer que la ventana de la lista se agrande cuando hay contenido y no quede un bloque blanco vacío abajo?

![image](https://user-images.githubusercontent.com/1755382/63379135-10f5ba80-c36a-11e9-86f8-51a875685850.png)

- [x] Es contraintuitivo que "volver a comenzar" vaya un paso atrás y la flecha de atrás, al principio. Lo invertiría.

![image](https://user-images.githubusercontent.com/1755382/63379482-c9bbf980-c36a-11e9-882f-047020e0920b.png)

- [x] Sería bueno tener algo (texto o imagen) para cuando no hay resultados (aplica a qué estudiar y a localidad)

![image](https://user-images.githubusercontent.com/1755382/63379225-426e8600-c36a-11e9-8c63-ecdc806e22ae.png)

- [x] Cambiar títulos a Primaria, Secundaria... y hacer los mismos cambios estéticos que se mencionan en la primer pantalla del formulario
- [x] No se ven los tags
- [x] La primera vez que abro la lista, no me anda, la segunda sí, la tercera no 🤔 
- [x] No me anda +info, me cierra la ventana

![image](https://user-images.githubusercontent.com/1755382/63379732-4b138c00-c36b-11e9-8ae6-ce92fe7839bb.png)

- [x] ¿Podemos poner el confirmar en un botón abajo del mapa? Mismo botón que "Continuar"
- [x] Cambiar el pin por el del diseño
- [x] No coloca el pin donde hago click... Como que tiene un error que se agranda con cada click. El primero está OK, el segundo no, el tercero ya es cualquiera

**Comment by fernandouval** [comment]
Cerrado
