### ISSUE TITLE
Repaso final - Resultado

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#65]
![image](https://user-images.githubusercontent.com/1755382/63379980-df7dee80-c36b-11e9-993b-d1961ec6e41a.png)

- [x] No se ve el pie en ésta página
- [x] Título pasa a "Éstos son los resultados para:"
- [x] Variables de búsqueda en gris, sin subrayado
- [x] "Agrupar" distancias de título, variables y botón de editar búsqueda
- [x] Sigue sin convencerme cómo se muestran las variables de búsqueda, parece un campo de texto pero no lo puedo editar. Los pasaría al formato tags.
- [x] Hay que editar la base para corregir las mayúsculas y los tildes de los cursos... 🙋‍♂ 
- [x] Agrandaría el botón de info para poder poner la frase "Más información del curso"
- [x] Tags a dos líneas de mínimo

NO TERMINÉ CON ÉSTA

**Comment by fernandouval** [comment]
Cerramos en general.
