### ISSUE TITLE
Carga de datos de Dispositivos y Programas

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#69]
[CFE - Nóveles Docentes.xlsx](https://drive.google.com/open?id=17uugpteHQKcouNZ52nqMScW6gVwm0drb)
[CFE - MENTA.xlsx](https://drive.google.com/open?id=1Ado61mQeTK3k41QtCXY93g_NQA-9g8Jp)
[CFE - Formación en Tecnologías Digitales para la Información.xlsx](https://drive.google.com/open?id=10-73II6tpWm2WiMNVkC-CJTSSu6orsZ3)
[CFE - CINEDUCA.xlsx](https://drive.google.com/open?id=1A2_kU_dqyrnz-6rrsYZM60d-MCkdSCkI)
[CFE - Aprender Todos.xlsx](https://drive.google.com/open?id=1l57ApSnqPDq6hTnBUe5DpDXEVtKkDIiD)
[CETP - Programa RUMBO.xlsx](https://drive.google.com/open?id=1xCiERYgHtXlHGN8Qo_1EUxLVzh_rJYLt)
[CETP - Formación Profesional Básica Plan 2007.xlsx](https://drive.google.com/open?id=1yZd-ysbHGcgc500GIar9mqLOkDzHQ87J)
[CES - Uruguay Estudia.xlsx](https://drive.google.com/open?id=1riFQDSSdepoWvI88jqhvat88hNy8cKpd)
[CES - Liceos con tutorías.xlsx](https://drive.google.com/open?id=1Ks6RfXVKKAS-4owpzvkSzf5notxfXzBX)
[CEIP - APRENDER.xlsx](https://drive.google.com/open?id=11N9Nh-bVCg9HeGrrg1GXK4io4bnf5yoy)
[CEIP - Programa Maestros Comunitarios.xlsx](https://drive.google.com/open?id=1NLjqO3NNOF1WkfVAjlCmsiomMmI18vND)
[CEIP - Programa Alimentación Escolar.xlsx](https://drive.google.com/open?id=1RjA70MgnNji_tKoF4JTXWnHsqWNG3cgv)
[CEIP - Escuelas de Tiempo Completo.xlsx](https://drive.google.com/open?id=1Nozwy-_nCyqvk6ErPqL4LI-F5wvtDqYV)
[CEIP - Dirección Sectorial de Jóvenes y Adultos.xlsx](https://drive.google.com/open?id=177BrPcCzrIZie7GVFFVL8IaHURhAjv6Z)

**Comment by fernandouval** [comment]
Se agregan vínculos a dispositivos
