### ISSUE TITLE
Preguntas frecuentes

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#70]
Redactar y cargar en Github

**Comment by danielcarranza** [comment]
Las empiezo en https://docs.google.com/document/d/1TJeNBIXfoy9AgCcxsbVPPyciPZfITJ4uFoXLQ5Q_oxQ/edit#heading=h.v9hpl3muxoy9

**Comment by fernandouval** [comment]
Esto no está @danielcarranza? Al sitio ya se subió una página...

**Comment by danielcarranza** [comment]
Si señor. Cierro.
