### ISSUE TITLE
Mayúsculas y tildes en datos originales

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#73]
- [x] CEIP https://drive.google.com/open?id=12IercKJJIVKQUqJiihw9yuavkZFVKyjf
- [x] CES https://drive.google.com/open?id=1HMx_K0bERAC2oTInOezUaAvmlZbopeum
- [x] CETP
- [x] CFE

**Comment by fernandouval** [comment]
Lista la nueva base en desarrollo
