### ISSUE TITLE
Adaptar diseño responsive a desktop

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#9]

**Comment by danielcarranza** [comment]
@despinoUY Fijate cuando hagas eso, de marcar un ancho máximo para los campos y para los modales, que no tiene sentido que sean gigantes en desktop.

**Comment by despinoUY** [comment]
@danielcarranza Estuve revisando los campos y modales y me parece que en desktop están en un tamaño razonable, pero lo podemos discutir en estos días.

**Comment by danielcarranza** [comment]
A mí y a @fernandouval nos parece que quedan enormes, le pondría una cota máxima de 500px a botones y campos.
