### ISSUE TITLE
Carga de mínimos y máximos de edad

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#95]
- [x] Edad mínima y máxima para tipos de curso
- [x] Edad mínima y máxima para planes
- [x] Filtrar listado (qué querés estudiar) según edad de la persona y tipo de curso que aplican
- [x] Filtrar resultados según edad de la persona y planes que aplican

Datos:
https://drive.google.com/file/d/1KtVqyEOhTtIOENJhLnBPD6JzdcYudEmc/view?usp=sharing

**Comment by fernandouval** [comment]
Se modifica la funcionalidad debido al funcionamiento actual de la plataforma:

1. La búsqueda de cursos se realiza a través de varios términos que  están agrupados sólamente dentro del curso, por lo que la misma se centra en los cursos.
2. Los planes están asociados también a los cursos, siendo que no existe el corte de planes más que como agrupación de los cursos en los diversos años que componen el plan, por lo que nuevamente la lógica se ubica en los cursos (la disquisición de los cursos por año es discutble, siendo que este dato podría ubicarse en la oferta y quizás tenga más sentido?)
VIendo esta disposición se agregan los campos de edad mínima y edad máxima a los cursos que serán filtrados en las llamadas.

**Comment by fernandouval** [comment]
## Procesamiento de edades
_Hay que dirimir la posibilidad de que el año se encuentre nucleado en la oferta? Estudiar la viabilidad o establecer un sistema mixto._  
Se crea importador con parámetros por plan  
Se detecta que dentro de los planes existe una variación de 2009 que contempla otro rango de edades, sin emabrgo a nivel de los datos existe un único plan 2009, por lo que la importación se hará considerando 15 años o más que cumple implementación CECAP hasta los 21 y de 21 en adelante del plan 2009.  
No hay planes 2016 en los datos 2019
