### ISSUE TITLE
Faltan URLs de planes

### ISSUE THREAD

**Issue by fernandouval** [datauy/ElijoEstudiar#98]
En detalle de centro en principio, hay que revisar filtros, al parecer son llamadas diferentes

**Comment by fernandouval** [comment]
NO hay nada implementado en el backend para los planes, por lo que a priori no hay forma de devolver los datos. Se pone a futuro ya que habría que ver si tenemos las descripciones de cursos según planes o son, como se manejaron hasta ahora según orientación o tipo de curso. 
De cualquier manera se pasa a futuro ya que no sería un cambio menor.

**Comment by danielcarranza** [comment]
Ok, entendido.

**Comment by fernandouval** [comment]
Se revisó el back y el dato estaba almacenado en el curso, por lo que se agregó el dato y ya se muestra, se pasa a hecho.
